### ISSUE TITLE
spatne odkazy v navigaci u stranky prvni-programy

### ISSUE THREAD

**Issue by ZelenyMartin** [podlomar/python-data#11]
Prosim te na strance:
http://nove.kodim.cz/czechitas/python-data/zaklady-programovani/prvni-programy/
Ta navigace nahore vede na:
http://nove.kodim.cz/czechitas/python-data/zaklady-programovani/prvni-programy/text-chroustani
http://nove.kodim.cz/czechitas/python-data/zaklady-programovani/prvni-programy/soubory
coz neplati. Nema tam byt to `prvni-programy` v ceste.
U jinych stranek jsem na problem neprisel.

**Comment by podlomar** [comment]
Děkuju, mrknu na to.

**Comment by ZelenyMartin** [comment]
Nesmi tam byt ten '/' na konci. Ale uz nevim, kde jsem se dostal k linku, kde ten '/' na konci byl. Nicmene ted uz to vsechno jede dobre.

**Comment by ZelenyMartin** [comment]
Prosim te, je tam takovy zarhel, ze kdyz na jakekoliv strance kliknu na anchor nejake kapitoly, tak ta navigace nahore prestane jet (ukazuje na neexistujici stranku, protoze je tam v ceste navic nazev te aktualni kapitoly).

**Comment by podlomar** [comment]
Ahoj Martine,

vím o tom. Řešení je ale mnohem hlubší a náročnější, než to vypadá. Souvisí to s tím, aby v materilálech na GitHubu i na webu byly funkčí cesty k obrázkům a dalším assets. Takže ještě mysím vymyslet nějaký chytrý způsob, jak to zařídit.

**Comment by podlomar** [comment]
Konečně vyřešeno! Můžeš vyzkoušet na webu.
