### ISSUE TITLE
Zmenit zapis do souboru

### ISSUE THREAD

**Issue by KSonny4** [podlomar/python-data#21]
Radime zapisovat `[soubor.write(jmeno) for jmeno in jmena]` . To musi prestat, plnime seznam `None` a v projektech by je to mohlo i kousnout. http://kodim.cz/kurzy/python-data/soubory/

**Comment by ZelenyMartin** [comment]
Mě se takový kus kódu taky k smrti nelíbí, ale muselo by se to upravit komplexněji. Chápu, že byl cíl mít práci se soubory v kurzu hodně vpředu, ale nevím, jestli to už není příliš. Možná bychom mohli prohodit kapitolu 5 a 6 s tím, že by se pak už mohl použít místo toho cyklus `for`. V kapitole [Podmínky](http://nove.kodim.cz/czechitas/python-data/zaklady-programovani/podminky-for/#podminky-pro-rizeni-behu) by se pak ale musel upravit první vzorový příklad na něco jiného (ještě by se v tu chvíli neznala práce se soubory).

**Comment by ZelenyMartin** [comment]
Bude vyřešeno podle návrhu v issue #32

**Comment by ZelenyMartin** [comment]
Vyřešeno v #36
