### ISSUE TITLE
Čtení a zápis do souboru

### ISSUE THREAD

**Issue by pesikj** [podlomar/python-data#32]
Ke čtení souboru bych používal metodu `readlines()`, číst a zapisovat to ručně pomocí cyklu není best-practice a je to zbytečně složité.

```
vstup = open('mereni.txt', encoding='utf-8')
radky = vstup.readlines()
```

Stejně tak zápis lze provádět pomocí `writelines()`.

```
jmena = ['Roman', 'Jana', 'Radek', 'Petra', 'Vlasta']
soubor = open('uzivatele.txt', 'w', encoding='utf-8')
soubor.writelines(jmena)
soubor.close()
```

**Comment by ZelenyMartin** [comment]
Souhlasím. To list comprehension je tam celkově strašně zneužity. Tím asi i můžeme vynechat cyklus `for` v této kapitole.

I přesto, že už jsme to s Martinem konzultovali, bych tady stejně rád měl v lekci `with` `as` - stejně to tak účím, nemůžu si pomoct.

**Comment by pesikj** [comment]
Ano, já bych to spíše udělal tak, že by ta kapitola o cyklech mohla navázat na tu o souborech (např. nejprve se naučím načíst soubor do seznamu a poté, až budu umět cyklus, si to můžu projet seznam položku po položce a třeba v tom něco hledat nebo upravovat).

**Comment by ZelenyMartin** [comment]
Vyřešeno v #36
