### ISSUE TITLE
Opravit odkaz v kapitole pandas-dotazy

### ISSUE THREAD

**Issue by lutydlitatova** [podlomar/python-data#51]
Chybný formát odkazu:

> Tabulku výše si můžete stáhnout ve [formátu CSV]{src=assets/mesta.csv}.

https://stage.kodim.cz/kurzy/python-data/datova-analyza/pandas-dotazy

**Comment by ZelenyMartin** [comment]
Vyreseno v https://github.com/podlomar/python-data/pull/58
