### ISSUE TITLE
Úprava přesměrování: Python data / DA / Pandas dotazy

### ISSUE THREAD

**Issue by Hedwika** [podlomar/python-data#52]
Hlásím minibug v [DA kapitole Pandas](https://kodim.cz/czechitas/python-data/datova-analyza/pandas-dotazy/#cviceni) - když v menu vlevo kliknu na druhé cvičení, přesměruje mě na první cvičení.

**Comment by ZelenyMartin** [comment]
Resolved in https://github.com/podlomar/python-data/pull/57
