### ISSUE TITLE
Přidat "Vlastní fukce"

### ISSUE THREAD

**Issue by ZelenyMartin** [podlomar/python-data#68]
Nejspíše do "První programy" [1] nebo "Podmínky a cyklus FOR". Já jsem to minule zvládl v [1], @pesikj to tuším učil v [2]. Kam to nejlépe přidat?

CC @lutydlitatova

[1] https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy
[2] https://kodim.cz/kurzy/python-data/zaklady-programovani/podminky-for

**Comment by pesikj** [comment]
Dal bych to do 2, případně bych navrhoval přesunout kapitolu o blocích, aby byla před vlastními funkcemi.

**Comment by ZelenyMartin** [comment]
Ahoj @pesikj,

navrhuji nedoplňovat text python-data, abychom neměli duplicity a prostě v lekci probrat to, co je v UdP2 [1]. Reopen v případě nesouhlasu.

[1] https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/funkce

**Comment by pesikj** [comment]
@ZelenyMartin Ano, souhlasím.
