### ISSUE TITLE
Průměr z průměrů

### ISSUE THREAD

**Issue by pesikj** [podlomar/python-data#76]
U příkladu [na chroustání seznamů](https://kodim.cz/kurzy/python-data/zaklady-programovani/text-chroustani/chroustani-seznamu#excs%3Eseznam-teplot) by bylo dobré přidat poznámku, že průměr z průměrů je možné použít pouze v případě, že je počet měření za všechny dny stejný.

**Comment by pesikj** [comment]
Navrhuji text: *Poznámka: V našem případě, kdy je počet měření pro každý den stejný, můžeme pro řešení bodu e) použít "průměr z průměrů", tedy průměr hodnot z bodu a).*
@lutydlitatova @ZelenyMartin

**Comment by ZelenyMartin** [comment]
Souhlasím. Taky jsem na to narazili. Buď upravit podle návrhu nebo úplně odstranit.

Nejsprávněji by se asi musely všechny teploty dát do jednoho seznamu
```
>>> teploty = [
...   [2.1, 5.2, 6.1, -0.1],
...   [2.2, 4.8, 5.6, -1.0],
...   [3.3, 6.5, 5.9, 1.2],
...   [2.9, 5.6, 6.0, 0.0],
...   [2.0, 4.6, 5.5, -1.2],
...   [1.0, 3.2, 2.1, -2.0],
...   [0.4, 2.7, 1.3, -2.8]
... ]
>>> vystup = []
>>> for den in teploty:
...     vystup.extend(den)
... 
>>> vystup
[2.1, 5.2, 6.1, -0.1, 2.2, 4.8, 5.6, -1.0, 3.3, 6.5, 5.9, 1.2, 2.9, 5.6, 6.0, 0.0, 2.0, 4.6, 5.5, -1.2, 1.0, 3.2, 2.1, -2.0, 0.4, 2.7, 1.3, -2.8]
```
Nebo takto:
```
>>> import itertools
>>> list(itertools.chain(*teploty))
[2.1, 5.2, 6.1, -0.1, 2.2, 4.8, 5.6, -1.0, 3.3, 6.5, 5.9, 1.2, 2.9, 5.6, 6.0, 0.0, 2.0, 4.6, 5.5, -1.2, 1.0, 3.2, 2.1, -2.0, 0.4, 2.7, 1.3, -2.8] 
```
Ale to asi nepatří do první hodiny.

**Comment by pesikj** [comment]
Já jsem ok i s tím, abychom ten bod dali úplně pryč. Počkejme, co řekne Lída :-)

**Comment by lutydlitatova** [comment]
Klidně se toho bodu můžeme zbavit, nebo ho nahradit (účastnice už umí `max` nebo `min`, tak to by se dalo využít).

**Comment by pesikj** [comment]
Tak tam můžeme dát rozpětí, tj. rozdíl mezi minimem a maximem. To už sice je v jedné volitelné úložce, ale tady by se to taky pěkně hodilo.

**Comment by ZelenyMartin** [comment]
Latka presunuta do https://kodim.cz/kurzy/uvod-do-progr-2/bonusy/cykly-2/list-comprehension

**Comment by ZelenyMartin** [comment]
Navrhuji bod **e** smazat: https://kodim.cz/kurzy/uvod-do-progr-2/bonusy/cykly-2/list-comprehension#excs%3Eseznam-teplot
