### ISSUE TITLE
cviceni Volby: posledni bod smazat - je to moc tezke

### ISSUE THREAD

**Issue by ZelenyMartin** [podlomar/python-data#77]
Smazat poslední bod cviceni https://kodim.cz/kurzy/python-data/zaklady-programovani/text-chroustani/cteni-na-doma#excs%3Evolby - asi se neda resit pomoci pouze probrane latky

**Comment by pesikj** [comment]
Převal jsem řešení, protože jsi @ZelenyMartin psal, že se teď nedostaneš k PC. Je to triviální a domluvená úprava, takže snad nevadí.
