### ISSUE TITLE
Odstranit cast, ktera popisuje instalaci pyreadline, nebo ji nahradit jinym resenim

### ISSUE THREAD

**Issue by pavelsuk** [podlomar/python-data#78]
Podkapitolka **Jaké jsou všechny metody řetězců?** v [Prace s textem|Retezce ](https://kodim.cz/kurzy/python-data/zaklady-programovani/text-chroustani/retezce) vyzaduje instalaci `pyreadline` , coz je v tom dost narocnym programu krok navic, ktery neni nezbytne nutny. Navic to vypada, ze `pyreadline` uz neni v Python 3.10 podporovana a na nekterych instalacich nefunguje vubec. 

Navrhovane moznosti reseni:

a) nahradit celou tuto sekci odkazem do dokumentace
b) nahradit to navodem na instalaci a pouzivani iPython
c) a+b

Vypada to, ze PR #73 tam zavedlo take instalaci `pyreadline`, tak by bylo dobre to vyresit v ramci tohoto ticketu na obou mistech jednotne.

**Comment by ZelenyMartin** [comment]
Diky moc. Poslu PR, kde to odstranim na obou mistech (pro objekty i moduly). Pak se domluvime co dal. Bod _b_, bych mozna ani kodim.cz nepsal a nechal to na lektorove vykladu, pokud to bude povazovat za vhodne.
