### ISSUE TITLE
Nefunguje odkaz z ulohy 2 a 3 v kapitole prvni programy

### ISSUE THREAD

**Issue by pavelsuk** [podlomar/python-data#81]
# Reported by Soustruh (slack)

Odkaz úlohy 3 nefunguje: https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy/prvni-programy

@pavelsuk nefunguje mi ani odkaz z Ulohy 2

Je mozne, ze problem je v tom, ze se na tu stranku da dostat pres ruzna URLka
1. https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy/
2. https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy/prvni-programy
ale kdyz si zkousim, kam to vede, tak je to v obou pripadech stejne na:

- https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy/hodnoty-promenne-funkce#excs%3Evyplata
- https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy/text-chroustani/chroustani-seznamu#excs%3Eseznam-teplot

Takze by to teoreticky mohlo jit fixnout jenom relativnim URLkem, posunutym o jednu uroven zpet. 

Kdyz to zkusim primo v browseru opravit na 
``` html
<a href="../hodnoty-promenne-funkce#excs%3Evyplata">cvičení na výpočet výplaty</a>
```
tak to zafunguje.

Zkusim to fixnout, ale bude to pak jeste chtit vyzkouset.

**Comment by ZelenyMartin** [comment]
Me to funguje, kdyz neklikam na ten levy panel:
![chrome-capture-2022-8-15](https://user-images.githubusercontent.com/20668450/190481933-c8bcc398-88ab-4b13-b82f-c6b30799d3d8.gif)
Mam obavu, ze navrzena uprava to treba opravi, kdyz tam pujde clovek pres ten panel, ale rozbije, kdyz tam pres ten panel nepujde.

Obavam se, ze se na to musi podivat @podlomar.

**Comment by pavelsuk** [comment]
Jo, to by to pak ta moje oprava vratila uplne do rootu, to je taky blby.

**Comment by pavelsuk** [comment]
Je to problem stejneho razu jako https://github.com/Czechitas-Python/uvod-do-progr-1/issues/28

**Comment by podlomar** [comment]
Opraveno ve verzi 1.5.7, viz https://kodim.cz/changelog/#v1.5.7

**Comment by pavelsuk** [comment]
Ted uz by to po zamerovani tohoto PR melo tim padem fungovat v obou dvou pripadech, protoze to URL je ve verzi 1.5.7 vzdycky

- https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy/prvni-programy a ten proklik by mel vest na 
- https://kodim.cz/kurzy/python-data/zaklady-programovani/hodnoty-promenne-funkce/hodnoty-promenne-funkce

Kdezto ted momentalne vede vzdycky na
- https://kodim.cz/kurzy/python-data/zaklady-programovani/prvni-programy/hodnoty-promenne-funkce#excs%3Evyplata

Kdyz si zkusim nasimulovat ten fix primo v browseru, tak mi to zafunguje, ale chtelo by to hned po mergi checknout. 

Muzete se na to jeste jednou nekdo (@pesikj @ZelenyMartin ) mrknout a pripadne zamergovat?
