### ISSUE TITLE
Zápis do slovníku

### ISSUE THREAD

**Issue by pesikj** [podlomar/python-data#93]
V kapitole o slovnících není příklad na zápis, bylo by dobré tam tu možnost mít popsanou také.

**Comment by ZelenyMartin** [comment]
Pravdepodobne by se to realizovalo az v ramci komplexnejsiho prepracovani textu na kodim.cz

**Comment by ZelenyMartin** [comment]
Zapis do slovniku je v UdP2: https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/slovniky/uvod

Toto repo zmizi z kodim.cz cele, takze zaviram issue.
