### ISSUE TITLE
Průchod seznamu slovníků pomocí cyklu

### ISSUE THREAD

**Issue by pesikj** [podlomar/python-data#94]
V materiálech je průchod pomocí list comprehension, ale bylo by dobré to ukázat pomocí cyklu, protože to je asi v realitě častější případ.

**Comment by ZelenyMartin** [comment]
Pravdepodobne by se to realizovalo az v ramci komplexnejsiho prepracovani textu na kodim.cz

**Comment by ZelenyMartin** [comment]
Ukazano v UdP2: https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/slovniky/dvourozmerne-tabulky

Toto repo zmizi z kodim.cz cele
