### ISSUE TITLE
Metoda append

### ISSUE THREAD

**Issue by pesikj** [podlomar/python-data#95]
Při práci se seznamy probrat metodu append, která byla vyřazena z ÚdP1.

**Comment by ZelenyMartin** [comment]
Pravdepodobne by se to realizovalo az v ramci komplexnejsiho prepracovani textu na kodim.cz

**Comment by ZelenyMartin** [comment]
Nachazi se v kapitole _Co všechno už umíme_: https://kodim.cz/kurzy/uvod-do-progr-2/uvod-do-programovani-2/uvod/sekvence. Podle me to tak staci.
